#
# Module manifest for module 'xSimpleTestResource'
#
# Generated by: Luffytaro
#
# Generated on: 1/24/2023
#

@{

RootModule = 'xSimpleTestResource.psm1'
ModuleVersion = '0.0.0.1'
GUID = 'a0be43e8-ac22-4244-8efc-7263dfa50b8c'
CompatiblePSEditions = 'Core'
Author = 'Luffytaro'
CompanyName = 'Microsoft Corporation'
Copyright = '(c) Microsoft Corporation. All rights reserved.'
Description = 'PowerShell module with DSC resources for unit tests'
PowerShellVersion = '7.2'
FunctionsToExport = @()
CmdletsToExport = @()
DscResourcesToExport = @(
    'SimpleFileResource'
    'SimpleTestResource'
    'SimpleTestResourceThrows'
    'SimpleTestResourceError'
)

}
