id: labelManagement.issueOpened
name: GitOps.PullRequestIssueManagement
description: Handlers for when an issue is first opened
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add CodeFlow link to new PRs
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addCodeFlowLink
      - description: Add Needs-Triage to new issues
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          - addLabel:
              label: Needs-Triage
      - description: Add area label for PowerShell Module
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: 'Relevant area\(s\)\s*\n.*PowerShell Module'
              isRegex: True
        then:
          - addLabel:
              label: PowerShell
      - description: Add area label for COM API
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: 'Relevant area\(s\)\s*\n.*COM API'
              isRegex: True
        then:
          - addLabel:
              label: Area-COM-API
      - description: Add area label for WinGet DSC Resources
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: 'Relevant area\(s\)\s*\n.*DSC Resource'
              isRegex: True
        then:
          - addLabel:
              label: DSC-Resource
onFailure:
onSuccess:
