id: labelManagement.issueClosed
name: GitOps.PullRequestIssueManagement
description: Handlers when an issue gets closed
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Remove labels when an issue is closed
        if:
          - payloadType: Issues
          - isAction:
              action: Closed
        then:
          - removeLabel:
              label: Needs-Triage
          - removeLabel:
              label: Needs-Attention
          - removeLabel:
              label: Needs-Author-Feedback
          - removeLabel:
              label: Help-Wanted
        ## TODO: Unassign author
      - description: Remove labels when a pull request is closed
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Closed
        then:
          - removeLabel:
              label: Needs-Attention
          - removeLabel:
              label: Needs-Author-Feedback
        ## TODO: Unassign Users
onFailure:
onSuccess:
