id: labelAdded.noRecentActivity
name: GitOps.PullRequestIssueManagement
description: Handlers when "No-Recent-Activity" label is added
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When the label "No-Recent-Activity" is added to a pull request
          * Add the PR specific reply notifying the issue author of pending closure
        if:
          - payloadType: Pull_Request
          - labelAdded:
              label: No-Recent-Activity
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},


                This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.


                Template: msftbot/noRecentActivity
        # The policy service should trigger even when the label was added by the policy service
        triggerOnOwnActions: true
      - description: >-
          When the label "No-Recent-Activity" is added to an issue
          * Add the issue specific reply notifying the issue author of pending closure
        if:
          - payloadType: Issues
          - labelAdded:
              label: No-Recent-Activity
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},


                This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.


                Template: msftbot/noRecentActivity
        # The policy service should trigger even when the label was added by the policy service
        triggerOnOwnActions: true
onFailure:
onSuccess:
