<#
.SYNOPSIS
    Registers the AppInstallerCLI package.
.DESCRIPTION
    Registers the loose files generated by the AppInstallerCLIPackage project
.PARAMETER BuildRoot
    The root of the build output directory.  If not provided, assumed to be the local default
    location relative to this script.
.PARAMETER PackageRoot
    The root of the package build output directory.  If not provided, assumed to be the local default
    location relative to this script.
#>
param(
    [Parameter(Mandatory=$false)]
    [string]$BuildRoot,

    [Parameter(Mandatory=$false)]
    [string]$PackageRoot
)
if ([String]::IsNullOrEmpty($BuildRoot))
{
    $BuildRoot = Split-Path -Parent $PSCommandPath;
    $BuildRoot = Join-Path $BuildRoot "..\x64\Debug";
}
$BuildRoot = Resolve-Path $BuildRoot
Write-Host "Using BuildRoot = $BuildRoot"

if ([String]::IsNullOrEmpty($PackageRoot))
{
    $PackageRoot = Split-Path -Parent $PSCommandPath;
    $PackageRoot = Join-Path $PackageRoot "..\AppInstallerCLIPackage\bin\x64\Debug";
}
$PackageRoot = Resolve-Path $PackageRoot
Write-Host "Using PackageRoot = $PackageRoot"

Get-AppxPackage WinGetDevCLI
Write-Host "Remove registered package"
Get-AppxPackage WinGetDevCLI | Remove-AppxPackage

$Local:BundlePackageFormat = Join-Path $PackageRoot "AppInstallerCLIPackage*.msixbundle"
$Local:ResolvedPackagePath = Resolve-Path $Local:BundlePackageFormat
$Local:ExtractedBundlePath = Join-Path $PackageRoot "ExtractedBundle"
$Local:BundleCopyPath = Join-Path $PackageRoot "bundle.zip"
Copy-Item -Path $Local:ResolvedPackagePath -Destination $Local:BundleCopyPath
Write-Host "Expanding bundle at: $Local:ResolvedPackagePath"
Expand-Archive -Path $Local:BundleCopyPath -DestinationPath $Local:ExtractedBundlePath

$Local:MainPackageFormat = Join-Path $Local:ExtractedBundlePath "AppInstallerCLIPackage*x86*.msix"
$Local:ResolvedMainPackagePath = Resolve-Path $Local:MainPackageFormat
$Local:ExtractedMainPath = Join-Path $PackageRoot "ExtractedMain"
$Local:MainCopyPath = Join-Path $PackageRoot "main.zip"
Copy-Item -Path $Local:ResolvedMainPackagePath -Destination $Local:MainCopyPath
Write-Host "Expanding package at: $Local:ResolvedMainPackagePath"
Expand-Archive -Path $Local:MainCopyPath -DestinationPath $Local:ExtractedMainPath

$Local:ManifestPath = Join-Path $ExtractedMainPath "AppxManifest.xml"
Write-Host "Registering manifest at path: $Local:ManifestPath"
Add-AppxPackage -Register $Local:ManifestPath

Get-AppxPackage WinGetDevCLI 

Write-Host "Enabling com tracing."
D:\a\1\s\tools\wpr\wpr.exe -start D:\a\1\s\tools\wpr\ComTrace.wprp -filemode

$Local:AppxRecipePath = Join-Path $BuildRoot "PackagedTests\x64\PackagedTests\PackagedTests.build.appxrecipe"
Write-Host "Running tests: $Local:AppxRecipePath"
& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "$Local:AppxRecipePath" "/logger:trx;LogFileName=D:\a\1\s\tools\wpr\traces\comTestRun.trx"
Write-Host "Finished Tests"
Write-Host "Ending com trace"
D:\a\1\s\tools\wpr\wpr.exe -stop D:\a\1\s\tools\wpr\traces\comTrace.etl
Write-Host "Ended com trace"