<#
.SYNOPSIS
    Removes the AppInstallerCLI package.
.DESCRIPTION
    Removes the loose files generated by the AppInstallerCLIPackage project
#>

Write-Host "Ending com trace"
& "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\tracelog.exe" -flush "COMBASE"
& "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\tracelog.exe" -flush "DCOMSCM"
& "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\tracelog.exe" -stop "COMBASE"
& "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\tracelog.exe" -stop "DCOMSCM"
Write-Host "Remove registered package"
Get-AppxPackage WinGetDevCLI | Remove-AppxPackage