<#
.SYNOPSIS
    Registers the AppInstallerCLI package.
.DESCRIPTION
    Registers the loose files generated by the AppInstallerCLIPackage project
.PARAMETER BuildRoot
    The root of the build output directory.  If not provided, assumed to be the local default
    location relative to this script.
.PARAMETER PackageRoot
    The root of the package build output directory.  If not provided, assumed to be the local default
    location relative to this script.
#>
param(
    [Parameter(Mandatory=$false)]
    [string]$BuildRoot,
    
    [Parameter(Mandatory=$false)]
    [string]$PackageRoot
)

if ([String]::IsNullOrEmpty($BuildRoot))
{
    $BuildRoot = Split-Path -Parent $PSCommandPath;
    $BuildRoot = Join-Path $BuildRoot "..\x64\Debug";
}
$BuildRoot = Resolve-Path $BuildRoot
Write-Host "Using BuildRoot = $BuildRoot"

if ([String]::IsNullOrEmpty($PackageRoot))
{
    $PackageRoot = Split-Path -Parent $PSCommandPath;
    $PackageRoot = Join-Path $PackageRoot "..\AppInstallerCLIPackage\bin\x64\Debug";
}
$PackageRoot = Resolve-Path $PackageRoot
Write-Host "Using PackageRoot = $PackageRoot"

# Register the package; this requires the local package to have been deployed at least once or it won't be built.
$Local:ManifestPath = Join-Path $PackageRoot "AppxManifest.xml"
if (-not (Test-Path $Local:ManifestPath))
{
    $Local:ManifestPath = Join-Path $PackageRoot "AppX\AppxManifest.xml"
}
Get-AppxPackage WinGetDevCLI 
Write-Host "Enabling com tracing."
D:\a\1\s\tools\wpr\wpr.exe -start D:\a\1\s\tools\wpr\ComTrace.wprp -filemode
Write-Host "Registering manifest at path: $Local:ManifestPath"
Add-AppxPackage -Register $Local:ManifestPath
Get-AppxPackage WinGetDevCLI 

$Local:AppxRecipePath = Join-Path $BuildRoot "PackagedTests\x64\PackagedTests\PackagedTests.build.appxrecipe"
Write-Host "Running tests: $Local:AppxRecipePath"
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" $Local:AppxRecipePath /logger:trx;LogFileName=D:\a\1\s\tools\wpr\traces\comTestRun.trx
Write-Host "Finished Tests"
Write-Host "Ending com trace"
D:\a\1\s\tools\wpr\wpr.exe -stop D:\a\1\s\tools\wpr\traces\comTrace.etl
Write-Host "Ended com trace"
