<#
.SYNOPSIS
    Removes the AppInstallerCLI package.
.DESCRIPTION
    Removes the loose files generated by the AppInstallerCLIPackage project
#>

Write-Host "Remove registered package"
Get-AppxPackage WinGetDevCLI | Remove-AppxPackage