parameters:
  dependsOn: build_projection

jobs:
- job: package_projection
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'windows-2019'
  strategy:
    maxParallel: 10
    matrix:
      Release_37_py:
        PyMajorVer: '3'
        PyMinorVer: '7'
      Release_38_py:
        PyMajorVer: '3'
        PyMinorVer: '8'
      Release_39_py:
        PyMajorVer: '3'
        PyMinorVer: '9'

  steps:
  
  - task: DownloadBuildArtifacts@0 
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: projection
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PyMajorVer).$(PyMinorVer).x'
      addToPath: true 

  - script: pip install wheel
    displayName: pip install wheel

  - template: steps-package-projection.yml
    parameters:
      architecture: x86
      pythonVersionSpec: '$(PyMajorVer).$(PyMinorVer).x'

  - template: steps-package-projection.yml
    parameters:
      architecture: amd64
      pythonVersionSpec: '$(PyMajorVer).$(PyMinorVer).x'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: wheel'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/wheel
      artifactName: wheel

