//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WinGet.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WinGet.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the catalog..
        /// </summary>
        internal static string CatalogConnectExceptionMessage {
            get {
                return ResourceManager.GetString("CatalogConnectExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cmdlet is currently disabled for SYSTEM..
        /// </summary>
        internal static string ExecuteAsSystemExceptionMessage {
            get {
                return ResourceManager.GetString("ExecuteAsSystemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching for packages: {0}.
        /// </summary>
        internal static string FindPackagesExceptionMessage {
            get {
                return ResourceManager.GetString("FindPackagesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source matches the given value: {0}.
        /// </summary>
        internal static string InvalidSourceExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidSourceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions matched the given value: {0}.
        /// </summary>
        internal static string InvalidVersionExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidVersionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages matched the given input criteria..
        /// </summary>
        internal static string NoPackageFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NoPackageFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos;.
        /// </summary>
        internal static string ProgressRecordActivityInstalling {
            get {
                return ResourceManager.GetString("ProgressRecordActivityInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling &apos;{0}&apos;.
        /// </summary>
        internal static string ProgressRecordActivityUninstalling {
            get {
                return ResourceManager.GetString("ProgressRecordActivityUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating &apos;{0}&apos;.
        /// </summary>
        internal static string ProgressRecordActivityUpdating {
            get {
                return ResourceManager.GetString("ProgressRecordActivityUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings file is invalid..
        /// </summary>
        internal static string UserSettingsReadException {
            get {
                return ResourceManager.GetString("UserSettingsReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, and {2} other packages matched the input criteria. Please refine the input..
        /// </summary>
        internal static string VagueCriteriaExceptionMessage {
            get {
                return ResourceManager.GetString("VagueCriteriaExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} failed with exit code {1}.
        /// </summary>
        internal static string WinGetCLIExceptionMessage {
            get {
                return ResourceManager.GetString("WinGetCLIExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute command; WinGet package not installed..
        /// </summary>
        internal static string WinGetPackageNotInstalledMessage {
            get {
                return ResourceManager.GetString("WinGetPackageNotInstalledMessage", resourceCulture);
            }
        }
    }
}
