//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WinGet.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WinGet.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to the source..
        /// </summary>
        internal static string ExceptionMessages_CatalogError {
            get {
                return ResourceManager.GetString("ExceptionMessages_CatalogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cmdlet is currently not available in an administrator context..
        /// </summary>
        internal static string ExceptionMessages_NoAdmin {
            get {
                return ResourceManager.GetString("ExceptionMessages_NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages matched the given input criteria..
        /// </summary>
        internal static string ExceptionMessages_NoPackagesFound {
            get {
                return ResourceManager.GetString("ExceptionMessages_NoPackagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error searching for packages..
        /// </summary>
        internal static string ExceptionMessages_SearchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessages_SearchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source with the given name was not found..
        /// </summary>
        internal static string ExceptionMessages_SourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionMessages_SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, &apos;{1}&apos;, and {2} other package(s) matched the input criteria. Please refine the input..
        /// </summary>
        internal static string ExceptionMessages_VagueSearch {
            get {
                return ResourceManager.GetString("ExceptionMessages_VagueSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version matched the given input criteria..
        /// </summary>
        internal static string ExceptionMessages_VersionNotFound {
            get {
                return ResourceManager.GetString("ExceptionMessages_VersionNotFound", resourceCulture);
            }
        }
    }
}
