//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WinGet.SharedLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GroupPolicyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupPolicyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WinGet.SharedLib.Resources.GroupPolicyResource", typeof(GroupPolicyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is disabled by Group Policy : {0}.
        /// </summary>
        internal static string ErrorBlockedByPolicy {
            get {
                return ResourceManager.GetString("ErrorBlockedByPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Additional Windows App Installer Sources.
        /// </summary>
        internal static string PolicyAdditionalSources {
            get {
                return ResourceManager.GetString("PolicyAdditionalSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Allowed Sources.
        /// </summary>
        internal static string PolicyAllowedSources {
            get {
                return ResourceManager.GetString("PolicyAllowedSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Microsoft Store Source Pinned Certificate Bypass.
        /// </summary>
        internal static string PolicyEnableBypassCertificatePinningForMicrosoftStore {
            get {
                return ResourceManager.GetString("PolicyEnableBypassCertificatePinningForMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Default Source.
        /// </summary>
        internal static string PolicyEnableDefaultSource {
            get {
                return ResourceManager.GetString("PolicyEnableDefaultSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Experimental Features.
        /// </summary>
        internal static string PolicyEnableExperimentalFeatures {
            get {
                return ResourceManager.GetString("PolicyEnableExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Hash Override.
        /// </summary>
        internal static string PolicyEnableHashOverride {
            get {
                return ResourceManager.GetString("PolicyEnableHashOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Local Archive Malware Scan Override.
        /// </summary>
        internal static string PolicyEnableLocalArchiveMalwareScanOverride {
            get {
                return ResourceManager.GetString("PolicyEnableLocalArchiveMalwareScanOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Local Manifest Files.
        /// </summary>
        internal static string PolicyEnableLocalManifests {
            get {
                return ResourceManager.GetString("PolicyEnableLocalManifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows App Installer Microsoft Store Source.
        /// </summary>
        internal static string PolicyEnableMSStoreSource {
            get {
                return ResourceManager.GetString("PolicyEnableMSStoreSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Package Manager proxy command line options.
        /// </summary>
        internal static string PolicyEnableProxyCommandLineOptions {
            get {
                return ResourceManager.GetString("PolicyEnableProxyCommandLineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Package Manager command line interfaces.
        /// </summary>
        internal static string PolicyEnableWindowsPackageManagerCommandLineInterfaces {
            get {
                return ResourceManager.GetString("PolicyEnableWindowsPackageManagerCommandLineInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Package Manager.
        /// </summary>
        internal static string PolicyEnableWinGet {
            get {
                return ResourceManager.GetString("PolicyEnableWinGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Package Manager Configuration.
        /// </summary>
        internal static string PolicyEnableWinGetConfiguration {
            get {
                return ResourceManager.GetString("PolicyEnableWinGetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Package Manager Settings.
        /// </summary>
        internal static string PolicyEnableWinGetSettings {
            get {
                return ResourceManager.GetString("PolicyEnableWinGetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when loading Windows Package Manager Group Policy Settings.
        /// </summary>
        internal static string PolicyLoadError {
            get {
                return ResourceManager.GetString("PolicyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when retrieving policy settings for the Group Policy : {0}.
        /// </summary>
        internal static string PolicyNotFound {
            get {
                return ResourceManager.GetString("PolicyNotFound", resourceCulture);
            }
        }
    }
}
