// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.Management.Configuration.Processor.Dsc
{
    [contractversion(1)]
    apicontract Contract{};

    [contract(Microsoft.Management.Configuration.Processor.Dsc.Contract, 1)]
    runtimeclass DscConfigurationSetProcessorFactory : [default] Microsoft.Management.Configuration.IConfigurationSetProcessorFactory
    {
        DscConfigurationSetProcessorFactory();
    }
}
