name: '📚 Documentation Issue'
description: Report issues in our documentation.
labels: ['Issue-Docs']
body:
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Could you describe which document needs to be corrected and why?
    validations:
      required: true
