// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#pragma once

// 0 is reserved to represent when there is no resource.
#define MANIFESTSCHEMA_NO_RESOURCE                      0

#define MANIFESTSCHEMA_RESOURCE_TYPE                  200

#define IDX_MANIFEST_SCHEMA_PREVIEW                   201

#define IDX_MANIFEST_SCHEMA_V1_SINGLETON              202
#define IDX_MANIFEST_SCHEMA_V1_VERSION                203
#define IDX_MANIFEST_SCHEMA_V1_INSTALLER              204
#define IDX_MANIFEST_SCHEMA_V1_DEFAULTLOCALE          205
#define IDX_MANIFEST_SCHEMA_V1_LOCALE                 206

#define IDX_MANIFEST_SCHEMA_V1_1_SINGLETON            207
#define IDX_MANIFEST_SCHEMA_V1_1_VERSION              208
#define IDX_MANIFEST_SCHEMA_V1_1_INSTALLER            209
#define IDX_MANIFEST_SCHEMA_V1_1_DEFAULTLOCALE        210
#define IDX_MANIFEST_SCHEMA_V1_1_LOCALE               211

#define IDX_MANIFEST_SCHEMA_V1_2_SINGLETON            212
#define IDX_MANIFEST_SCHEMA_V1_2_VERSION              213
#define IDX_MANIFEST_SCHEMA_V1_2_INSTALLER            214
#define IDX_MANIFEST_SCHEMA_V1_2_DEFAULTLOCALE        215
#define IDX_MANIFEST_SCHEMA_V1_2_LOCALE               216

#define IDX_MANIFEST_SCHEMA_V1_4_SINGLETON            217
#define IDX_MANIFEST_SCHEMA_V1_4_VERSION              218
#define IDX_MANIFEST_SCHEMA_V1_4_INSTALLER            219
#define IDX_MANIFEST_SCHEMA_V1_4_DEFAULTLOCALE        220
#define IDX_MANIFEST_SCHEMA_V1_4_LOCALE               221

#define IDX_MANIFEST_SCHEMA_V1_5_SINGLETON            222
#define IDX_MANIFEST_SCHEMA_V1_5_VERSION              223
#define IDX_MANIFEST_SCHEMA_V1_5_INSTALLER            224
#define IDX_MANIFEST_SCHEMA_V1_5_DEFAULTLOCALE        225
#define IDX_MANIFEST_SCHEMA_V1_5_LOCALE               226

#define IDX_MANIFEST_SCHEMA_V1_6_SINGLETON            227
#define IDX_MANIFEST_SCHEMA_V1_6_VERSION              228
#define IDX_MANIFEST_SCHEMA_V1_6_INSTALLER            229
#define IDX_MANIFEST_SCHEMA_V1_6_DEFAULTLOCALE        230
#define IDX_MANIFEST_SCHEMA_V1_6_LOCALE               231

#define IDX_MANIFEST_SCHEMA_V1_7_SINGLETON            232
#define IDX_MANIFEST_SCHEMA_V1_7_VERSION              233
#define IDX_MANIFEST_SCHEMA_V1_7_INSTALLER            234
#define IDX_MANIFEST_SCHEMA_V1_7_DEFAULTLOCALE        235
#define IDX_MANIFEST_SCHEMA_V1_7_LOCALE               236

#define IDX_MANIFEST_SCHEMA_V1_9_SINGLETON            237
#define IDX_MANIFEST_SCHEMA_V1_9_VERSION              238
#define IDX_MANIFEST_SCHEMA_V1_9_INSTALLER            239
#define IDX_MANIFEST_SCHEMA_V1_9_DEFAULTLOCALE        240
#define IDX_MANIFEST_SCHEMA_V1_9_LOCALE               241

#define IDX_MANIFEST_SCHEMA_V1_10_SINGLETON           242
#define IDX_MANIFEST_SCHEMA_V1_10_VERSION             243
#define IDX_MANIFEST_SCHEMA_V1_10_INSTALLER           244
#define IDX_MANIFEST_SCHEMA_V1_10_DEFAULTLOCALE       245
#define IDX_MANIFEST_SCHEMA_V1_10_LOCALE              246
