set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_C_FLAGS "/Qspectre /W3")
set(VCPKG_CXX_FLAGS "/Qspectre /W3")
set(VCPKG_BUILD_TYPE release)
