//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WinGet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WinGet.Configuration.Engine.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts the configuration warning, preventing an interactive prompt.
        /// </summary>
        internal static string ConfigurationAcceptWarningArgumentDescription {
            get {
                return ResourceManager.GetString("ConfigurationAcceptWarningArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `-ModulePath AllUsers` require administrator privileges to execute..
        /// </summary>
        internal static string ConfigurationAllUsersElevated {
            get {
                return ResourceManager.GetString("ConfigurationAllUsersElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ConfigurationApply {
            get {
                return ResourceManager.GetString("ConfigurationApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.
        /// </summary>
        internal static string ConfigurationAssert {
            get {
                return ResourceManager.GetString("ConfigurationAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:{0}.
        /// </summary>
        internal static string ConfigurationDependencies {
            get {
                return ResourceManager.GetString("ConfigurationDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;See the log file for additional details&gt;.
        /// </summary>
        internal static string ConfigurationDescriptionWasTruncated {
            get {
                return ResourceManager.GetString("ConfigurationDescriptionWasTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the configuration was not applied successfully..
        /// </summary>
        internal static string ConfigurationFailedToApply {
            get {
                return ResourceManager.GetString("ConfigurationFailedToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get detailed information about the configuration..
        /// </summary>
        internal static string ConfigurationFailedToGetDetails {
            get {
                return ResourceManager.GetString("ConfigurationFailedToGetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; in the configuration file is the wrong type..
        /// </summary>
        internal static string ConfigurationFieldInvalidType {
            get {
                return ResourceManager.GetString("ConfigurationFieldInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; has an invalid value: {1}.
        /// </summary>
        internal static string ConfigurationFieldInvalidValue {
            get {
                return ResourceManager.GetString("ConfigurationFieldInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is missing or empty..
        /// </summary>
        internal static string ConfigurationFieldMissing {
            get {
                return ResourceManager.GetString("ConfigurationFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the configuration file..
        /// </summary>
        internal static string ConfigurationFileArgumentDescription {
            get {
                return ResourceManager.GetString("ConfigurationFileArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration is empty..
        /// </summary>
        internal static string ConfigurationFileEmpty {
            get {
                return ResourceManager.GetString("ConfigurationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is invalid..
        /// </summary>
        internal static string ConfigurationFileInvalid {
            get {
                return ResourceManager.GetString("ConfigurationFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file version {0} is not known..
        /// </summary>
        internal static string ConfigurationFileVersionUnknown {
            get {
                return ResourceManager.GetString("ConfigurationFileVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving configuration details.
        /// </summary>
        internal static string ConfigurationGettingDetails {
            get {
                return ResourceManager.GetString("ConfigurationGettingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform.
        /// </summary>
        internal static string ConfigurationInform {
            get {
                return ResourceManager.GetString("ConfigurationInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing configuration system.
        /// </summary>
        internal static string ConfigurationInitializing {
            get {
                return ResourceManager.GetString("ConfigurationInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string ConfigurationLocal {
            get {
                return ResourceManager.GetString("ConfigurationLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0}.
        /// </summary>
        internal static string ConfigurationModuleNameOnly {
            get {
                return ResourceManager.GetString("ConfigurationModuleNameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `-ModulePath` value must be `CurrentUser`, `AllUsers`, `Default` or an absolute path..
        /// </summary>
        internal static string ConfigurationModulePathArgError {
            get {
                return ResourceManager.GetString("ConfigurationModulePathArgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0} by {1} [{2}].
        /// </summary>
        internal static string ConfigurationModuleWithDetails {
            get {
                return ResourceManager.GetString("ConfigurationModuleWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration file.
        /// </summary>
        internal static string ConfigurationReadingConfigFile {
            get {
                return ResourceManager.GetString("ConfigurationReadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration history.
        /// </summary>
        internal static string ConfigurationReadingConfigHistory {
            get {
                return ResourceManager.GetString("ConfigurationReadingConfigHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        internal static string ConfigurationSettings {
            get {
                return ResourceManager.GetString("ConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration successfully applied..
        /// </summary>
        internal static string ConfigurationSuccessfullyApplied {
            get {
                return ResourceManager.GetString("ConfigurationSuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is not in the desired state asserted by the configuration..
        /// </summary>
        internal static string ConfigurationUnitAssertHadNegativeResult {
            get {
                return ResourceManager.GetString("ConfigurationUnitAssertHadNegativeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration unit failed for an unknown reason: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailed {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed due to the configuration: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailedConfigSet {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedConfigSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed while attempting to get the current system state..
        /// </summary>
        internal static string ConfigurationUnitFailedDuringGet {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedDuringGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed while attempting to apply the desired state..
        /// </summary>
        internal static string ConfigurationUnitFailedDuringSet {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedDuringSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed while attempting to test the current system state..
        /// </summary>
        internal static string ConfigurationUnitFailedDuringTest {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedDuringTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed due to an internal error: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailedInternal {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed due to a precondition not being valid: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailedPrecondition {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed due to the system state: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailedSystemState {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedSystemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit failed while attempting to run: {0}.
        /// </summary>
        internal static string ConfigurationUnitFailedUnitProcessing {
            get {
                return ResourceManager.GetString("ConfigurationUnitFailedUnitProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration contains the identifier `{0}` multiple times..
        /// </summary>
        internal static string ConfigurationUnitHasDuplicateIdentifier {
            get {
                return ResourceManager.GetString("ConfigurationUnitHasDuplicateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency `{0}` was not found within the configuration..
        /// </summary>
        internal static string ConfigurationUnitHasMissingDependency {
            get {
                return ResourceManager.GetString("ConfigurationUnitHasMissingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration unit was manually skipped..
        /// </summary>
        internal static string ConfigurationUnitManuallySkipped {
            get {
                return ResourceManager.GetString("ConfigurationUnitManuallySkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module for the configuration unit is available in multiple locations with the same version..
        /// </summary>
        internal static string ConfigurationUnitModuleConflict {
            get {
                return ResourceManager.GetString("ConfigurationUnitModuleConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the module for the configuration unit failed..
        /// </summary>
        internal static string ConfigurationUnitModuleImportFailed {
            get {
                return ResourceManager.GetString("ConfigurationUnitModuleImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple matches were found for the configuration unit; specify the module to select the correct one..
        /// </summary>
        internal static string ConfigurationUnitMultipleMatches {
            get {
                return ResourceManager.GetString("ConfigurationUnitMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit could not be found..
        /// </summary>
        internal static string ConfigurationUnitNotFound {
            get {
                return ResourceManager.GetString("ConfigurationUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit was not in the module as expected..
        /// </summary>
        internal static string ConfigurationUnitNotFoundInModule {
            get {
                return ResourceManager.GetString("ConfigurationUnitNotFoundInModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration unit was not run because a dependency failed or was not run..
        /// </summary>
        internal static string ConfigurationUnitNotRunDueToDependency {
            get {
                return ResourceManager.GetString("ConfigurationUnitNotRunDueToDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration unit was not run because an assert failed or was false..
        /// </summary>
        internal static string ConfigurationUnitNotRunDueToFailedAssert {
            get {
                return ResourceManager.GetString("ConfigurationUnitNotRunDueToFailedAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration unit returned an unexpected result during execution..
        /// </summary>
        internal static string ConfigurationUnitReturnedInvalidResult {
            get {
                return ResourceManager.GetString("ConfigurationUnitReturnedInvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration unit was not run for an unknown reason: {0}.
        /// </summary>
        internal static string ConfigurationUnitSkipped {
            get {
                return ResourceManager.GetString("ConfigurationUnitSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another configuration is being applied to the system. This configuration will continue as soon as is possible....
        /// </summary>
        internal static string ConfigurationWaitingOnAnother {
            get {
                return ResourceManager.GetString("ConfigurationWaitingOnAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are responsible for understanding the configuration settings you are choosing to execute. Microsoft is not responsible for the configuration file you have authored or imported. This configuration may change settings in Windows, install software, change software settings (including security settings), and accept user agreements to third-party packages and services on your behalf.  By running this configuration file, you acknowledge that you understand and agree to these resources and settings. Any applic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationWarning {
            get {
                return ResourceManager.GetString("ConfigurationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you reviewed the configuration and would you like to proceed applying it to the system?.
        /// </summary>
        internal static string ConfigurationWarningPromptApply {
            get {
                return ResourceManager.GetString("ConfigurationWarningPromptApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you reviewed the configuration and would you like to proceed verifying it against the system?.
        /// </summary>
        internal static string ConfigurationWarningPromptTest {
            get {
                return ResourceManager.GetString("ConfigurationWarningPromptTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug parameter not supported.
        /// </summary>
        internal static string DebugNotSupported {
            get {
                return ResourceManager.GetString("DebugNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See line {0}, column {1} in the file..
        /// </summary>
        internal static string SeeLineAndColumn {
            get {
                return ResourceManager.GetString("SeeLineAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the module for the configuration unit failed because it requires administrator privileges to run..
        /// </summary>
        internal static string WinGetConfigUnitImportModuleAdmin {
            get {
                return ResourceManager.GetString("WinGetConfigUnitImportModuleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unit contains a setting that requires the config root..
        /// </summary>
        internal static string WinGetConfigUnitSettingConfigRoot {
            get {
                return ResourceManager.GetString("WinGetConfigUnitSettingConfigRoot", resourceCulture);
            }
        }
    }
}
