name: Main Build (Windows)

on:
  push:
    branches: [ "main" ]

# Permissions and environment values to be able to update the dependency graph with vcpkg information
# and to enable the writing/uploading of CodeQL scan results
permissions:
  contents: write
  security-events: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build-windows:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: ./.github/workflows/initialize-codeql

      - name: Install Winget
        uses: ./.github/workflows/install-winget

      - name: Setup
        shell: pwsh
        run: .\scripts\Setup.ps1

      - name: Build and Test (no test overrides)
        shell: pwsh
        run: |
          .\scripts\Build.ps1
          .\scripts\Test.ps1 -OutputOnFailure

      - name: Build and Test (with test overrides)
        shell: pwsh
        run: |
          .\scripts\Build.ps1 -EnableTestOverrides
          .\scripts\Test.ps1 -OutputOnFailure

      - name: Build and Test (Release)
        shell: pwsh
        run: |
            .\scripts\Build.ps1 -BuildType Release
            .\scripts\Test.ps1 -OutputOnFailure
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
