name: Spell checking
on:
  pull_request_target:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 5
    - uses: check-spelling/check-spelling@0.0.17-alpha
