// -----------------------------------------------------------------------------
// <copyright file="IWinGetSQLiteIndex.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. Licensed under the MIT License.
// </copyright>
// -----------------------------------------------------------------------------

namespace Microsoft.WinGetUtil.Interfaces
{
    using System;

    /// <summary>
    /// The properties that can be set with IWinGetSQLiteIndex::SetProperty.
    /// The values must match those in WinGetUtil.h.
    /// </summary>
    public enum SQLiteIndexProperty
    {
        /// <summary>
        /// The base time to use for update tracking. The value is in the Unix epoch.
        /// Set to an empty string to use the current time.
        /// Set to 0 to force all files to be output.
        /// </summary>
        PackageUpdateTrackingBaseTime = 0,

        /// <summary>
        /// The full path to a base directory where intermediate files will be output.
        /// The path does not need to exist, and may not be created if no files need to be written.
        /// </summary>
        IntermediateFileOutputPath = 1,

        /// <summary>
        /// The full path to the baseline index that a delta index should be generated against.
        /// The baseline must have been produced with <see cref="DeltaMarkAsBaseline"/> set.
        /// Mutually exclusive with <see cref="DeltaMarkAsBaseline"/>; exactly one of the two must be
        /// set, along with all of the other delta properties, for a delta to be generated by
        /// <see cref="IWinGetSQLiteIndex.PrepareForPackaging"/>. Setting none of them leaves it unchanged.
        /// </summary>
        DeltaBaselineIndexPath = 2,

        /// <summary>
        /// The full path that the generated delta index should be written to.
        /// A file must not already exist at this location.
        /// </summary>
        DeltaOutputPath = 3,

        /// <summary>
        /// The location of the baseline package, relative to the source's base location.
        /// This allows versioned baselines to exist and be independently controlled by the service.
        /// </summary>
        DeltaBaselineRelativeSourcePath = 4,

        /// <summary>
        /// The version of the baseline package, which makes some of the client side checks more efficient.
        /// </summary>
        DeltaBaselinePackageVersion = 5,

        /// <summary>
        /// Designates the index being prepared as a baseline that later delta indexes may be
        /// generated against, in place of naming an existing one. The delta that is produced
        /// alongside it is empty, since the index is its own baseline.
        /// The only valid value is "true"; mutually exclusive with <see cref="DeltaBaselineIndexPath"/>.
        /// </summary>
        DeltaMarkAsBaseline = 6,

        /// <summary>
        /// The full path to the standard index built from the same data as a delta.
        /// Only meaningful when checking the consistency of a delta that has also been given
        /// <see cref="DeltaBaselineIndexPath"/>; the merged result of the delta and its baseline
        /// must present the same data as this index.
        /// </summary>
        DeltaComparisonIndexPath = 7,
    }

    /// <summary>
    /// Interface for index operations.
    /// </summary>
    public interface IWinGetSQLiteIndex : IDisposable
    {
        /// <summary>
        /// Migrates the index to the given version.
        /// </summary>
        /// <param name="majorVersion">Major version.</param>
        /// <param name="minorVersion">Minor version.</param>
        void MigrateTo(uint majorVersion, uint minorVersion);

        /// <summary>
        /// Sets the given property to the given value.
        /// </summary>
        /// <param name="property">The property to set.</param>
        /// <param name="value">The value to set.</param>
        void SetProperty(SQLiteIndexProperty property, string value);

        /// <summary>
        /// Adds manifest to index.
        /// </summary>
        /// <param name="manifestPath">Manifest to add.</param>
        /// <param name="relativePath">Path of the manifest in the repository.</param>
        void AddManifest(string manifestPath, string relativePath);

        /// <summary>
        /// Updates manifest in the index.
        /// </summary>
        /// <param name="manifestPath">Path to manifest to modify.</param>
        /// <param name="relativePath">Path of the manifest in the repository.</param>
        /// <returns>True if index was modified.</returns>
        bool UpdateManifest(string manifestPath, string relativePath);

        /// <summary>
        /// Adds or Updates manifest in the index.
        /// </summary>
        /// <param name="manifestPath">Path to manifest.</param>
        /// <param name="relativePath">Path of the manifest in the repository.</param>
        /// <returns>True if added; false if updated.</returns>
        bool AddOrUpdateManifest(string manifestPath, string relativePath);

        /// <summary>
        /// Delete manifest from index.
        /// </summary>
        /// <param name="manifestPath">Path to manifest to modify.</param>
        /// <param name="relativePath">Path of the manifest in the repository.</param>
        void RemoveManifest(string manifestPath, string relativePath);

        /// <summary>
        /// Wrapper for WinGetSQLiteIndexPrepareForPackaging.
        /// </summary>
        void PrepareForPackaging();

        /// <summary>
        /// Checks the index for consistency, ensuring that at a minimum all referenced rows actually exist.
        /// </summary>
        /// <returns>Is index consistent.</returns>
        bool IsIndexConsistent();

        /// <summary>
        /// Gets the managed index handle. It is used in additional manifest validation that requires an index.
        /// </summary>
        /// <returns>The managed index handle.</returns>
        IntPtr GetIndexHandle();
    }
}
